export const ERROR_CODES = {
  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',
  OUT_OF_RANGE: 'OUT_OF_RANGE',

  // Profile Errors
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_ALREADY_EXISTS: 'PROFILE_ALREADY_EXISTS',
  PROFILE_EXPIRED: 'PROFILE_EXPIRED',
  PROFILE_INACTIVE: 'PROFILE_INACTIVE',
  QR_CODE_NOT_GENERATED: 'QR_CODE_NOT_GENERATED',

  // Payment Errors
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
  PAYMENT_INSUFFICIENT_AMOUNT: 'PAYMENT_INSUFFICIENT_AMOUNT',
  PAYMENT_PROCESSING_FAILED: 'PAYMENT_PROCESSING_FAILED',
  INVALID_PAYMENT_METHOD: 'INVALID_PAYMENT_METHOD',

  // User Errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_BLOCKED: 'USER_BLOCKED',
  USER_EMAIL_NOT_VERIFIED: 'USER_EMAIL_NOT_VERIFIED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // System Errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
} as const;

export const ERROR_MESSAGES = {
  [ERROR_CODES.PROFILE_NOT_FOUND]: 'Perfil não encontrado',
  [ERROR_CODES.PROFILE_ALREADY_EXISTS]: 'Perfil já existe com este email/CPF',
  [ERROR_CODES.PROFILE_EXPIRED]: 'Assinatura do perfil expirada',
  [ERROR_CODES.PAYMENT_NOT_FOUND]: 'Pagamento não encontrado',
  [ERROR_CODES.PAYMENT_PROCESSING_FAILED]: 'Falha ao processar pagamento',
  [ERROR_CODES.USER_NOT_FOUND]: 'Usuário não encontrado',
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Credenciais inválidas',
  [ERROR_CODES.DATABASE_ERROR]: 'Erro interno do banco de dados',
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 'Erro no serviço externo'
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;